import { StyleSheet } from "react-native";

export default StyleSheet.create({
  topHUD: {
    position: "absolute",
    top: 40,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 20,
  },
  player1Score: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  coins: {
    fontSize: 20,
    fontWeight: "bold",
    color: "gold",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  gems: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#00ffff",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  comboText: {
    position: "absolute",
    top: 100,
    alignSelf: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "#ff6600",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  livesText: {
    position: "absolute",
    top: 40,
    right: 20,
    fontSize: 20,
    fontWeight: "bold",
    color: "red",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});